### ISSUE TITLE
Tracking: Rename to Nala

### ISSUE THREAD

**Issue by petemill** [brave/leo#406]
- [x] Rename the deploy hostname
- [ ] Rename the repo
- [ ] Rename the css variables and tag names
- [ ] Documentation
