### ISSUE TITLE
[META ISSUE] Rounded rectangle updates

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#509]
Adding this meta issue here based on a new shape in our buttons and how it affects a lot of related components.

```[tasklist]
### Updates
- [ ] Buttons https://github.com/brave/leo/issues/510
- [ ] Segmented control https://github.com/brave/leo/issues/511
- [ ] Dropdown values https://github.com/brave/leo/issues/514
- [ ] Input fields values https://github.com/brave/leo/issues/567
- [ ] Alerts and toasts - New buttons placement update https://github.com/brave/leo/issues/515
```

**Comment by AlanBreck** [comment]
Beginnings: https://github.com/brave/leo/pull/523

**Comment by fallaciousreasoning** [comment]
We're not doing rounded rectangles now, right @aguscruiz ?

**Comment by aguscruiz** [comment]
We already have it, that's the shape of our buttons now
