### ISSUE TITLE
List of component changes with Material color update

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#682]
```[tasklist]
### Tasks
- [ ] Label colors. Default backgrounds change from themable 10 to 20.
- [ ] Toggle colors change, all of them.
- [ ] All themable colors and semantic colors change to adapt to new primitives
- [ ] Buttons change and now have light-dark themes in filled buttons
- [ ] Default icon color changes
- [ ] Default text styles color changes
- [ ] IT would be ideal if we could add aliases for each color that references another. Would make it easier to change things in the future?
- [ ] Updated elevation values
- [ ] Updated focus state: Created one style for buttons and one style for everything else as a stroke variable
```
