### ISSUE TITLE
[Tracking] - List of adjustments / Dec2024

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#949]
```[tasklist]
### Fonts
- [ ] Heading fonts changed to inter with stylistic variants
- [ ] Buttons changed oto inter with stylistic variants
- [ ] All regular fonts have Inter variants too
``` 

```[tasklist]
### Design tweaks
- [ ] Text input now has a divider/subtle outline
```
